spring:
  application:
    name: book-trading-system
  datasource:
    url: jdbc:mysql://localhost:3305/book_trading_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.booktrading.server.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: book_trading_system_secret_key
  expiration: 86400
